global:
  slack_api_url: 'https://hooks.slack.com/services/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'
  group_by: ['alertname']
  group_wait: 5s
  group_interval: 1m
  repeat_interval: 10m
  receiver: 'slack'

receivers:
- name: 'slack'
  slack_configs:
  - channel: '#alerts'
    icon_emoji: ':bell:'
    send_resolved: true
    text: "<!channel> \nsummary: {{ .CommonAnnotations.message }}\n"
