apiVersion: v1
kind: Service
metadata: 
  name: fleetman-webapp
spec: 
  #  This defines which pods are going to e represensed by this Service
  # The service becomes a network endport for either other services 
  # or maybe external users to connect to (eg. browser)
  selector:
  app:webapp
ports:
  - name:
